--~ // Licensed under the Apache License, Version 2.0. See LICENSE.txt in the project root for license information.

require("QuikSharp")

-- Do not edit this file. Just copy it and save with a different name. Then write required params for it inside config.json file
-- Не редактируйте этой файл. Просто скопируйте и сохраните под другим именем. После этого укажите настройки для него в файле config.json

function main()
    if setup(scriptFilename()) then
        run()
    end
end