// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("QuikSharp")]
[assembly: AssemblyProductAttribute("QuikSharp")]
[assembly: AssemblyDescriptionAttribute("Quik Lua interface in .NET")]
[assembly: AssemblyVersionAttribute("0.3.0")]
[assembly: AssemblyFileVersionAttribute("0.3.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.3.0";
    }
}
