// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("QuikStarter")]
[assembly: AssemblyProductAttribute("QuikSharp")]
[assembly: AssemblyDescriptionAttribute("Quik Lua interface in .NET")]
[assembly: AssemblyVersionAttribute("0.1.1")]
[assembly: AssemblyFileVersionAttribute("0.1.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.1";
    }
}
